version: "3.9"

services:
  backend-security-groups:
    build: ./services/security-groups
    container_name: backend-security-groups
    expose:
      - "8000"           
    environment:
      - AWS_REGION=ap-northeast-2
    networks:
      - appnet

  backend-home:
    build: ./services/login-role
    container_name: backend-home
    expose:
      - "8000"
    environment:
      - AWS_REGION=ap-northeast-2
    networks:
      - appnet

  backend-s3:
    build: ./services/s3
    container_name: backend-s3
    expose:
      - "8000"
    environment:
      - AWS_REGION=ap-northeast-2
    networks:
      - appnet

  backend-ec2:
    build: ./services/ec2s
    container_name: backend-ec2
    expose:
      - "8000"
    environment:
      - AWS_REGION=ap-northeast-2
    networks:
      - appnet

  backend-network:
    build: ./services/network
    container_name: backend-network
    expose:
      - "8000"
    environment:
      - AWS_REGION=ap-northeast-2
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80" 
      - "443:443"     
    depends_on:
      - backend-security-groups
      - backend-home
      - backend-ec2
      - backend-s3
      - backend-network
    networks:
      - appnet
    restart: always
    environment:
      - VIRTUAL_HOST=awsdocumenting.com
      - VIRTUAL_PORT=80

networks:
  appnet:
    driver: bridge
